"""Saudi-market demo opportunities source with runtime-generated dates."""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any


class SaudiDemoOpportunitiesService:
    """Generate realistic Saudi demo opportunities for jobs, coop, and GDP."""

    _TEMPLATES: list[dict[str, Any]] = [
        {
            "id": "saudi_job_stc_backend",
            "company_name": "STC",
            "company_description": "STC is one of Saudi Arabia's leading digital enablers, operating large-scale telecom, cloud, and enterprise platforms.",
            "job_title": "Backend Engineer",
            "job_description": "Build internal APIs and digital customer services for high-traffic telecom products, with a focus on reliability and integration.",
            "requirements": [
                "2+ years building backend services in Python or Node.js",
                "Experience designing REST APIs and working with relational databases",
                "Comfort collaborating with QA, DevOps, and product teams",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "14000-18000 SAR/month",
            "required_skills": ["Python", "FastAPI", "SQL", "Docker", "Git"],
            "application_email": "careers@stc.com.sa",
            "posted_days_ago": 1,
            "deadline_days_after_posted": 18,
        },
        {
            "id": "saudi_job_elm_product",
            "company_name": "Elm",
            "company_description": "Elm builds digital products and data-driven public sector services across Saudi Arabia.",
            "job_title": "Technical Product Analyst",
            "job_description": "Partner with product managers and engineering teams to define requirements, track product metrics, and support delivery of digital services.",
            "requirements": [
                "Strong analytical communication and stakeholder management",
                "Ability to translate product needs into structured requirements",
                "Experience with dashboards or product analytics tools is a plus",
            ],
            "category": "jobs",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "12000-15500 SAR/month",
            "required_skills": ["Product Analytics", "SQL", "Data Analysis", "Communication"],
            "application_email": "jobs@elm.sa",
            "posted_days_ago": 3,
            "deadline_days_after_posted": 21,
        },
        {
            "id": "saudi_job_sdaia_data",
            "company_name": "SDAIA",
            "company_description": "SDAIA leads national data and AI initiatives supporting Saudi Arabia's digital transformation agenda.",
            "job_title": "Data Engineer",
            "job_description": "Develop data pipelines and analytics-ready datasets for public-sector AI and reporting initiatives.",
            "requirements": [
                "Experience with ETL pipelines and cloud data workflows",
                "Solid SQL and Python foundations",
                "Understanding of data quality and governance practices",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "15000-19000 SAR/month",
            "required_skills": ["Python", "SQL", "AWS", "Data Engineering", "Linux"],
            "application_email": "talent@sdaia.gov.sa",
            "posted_days_ago": 6,
            "deadline_days_after_posted": 24,
        },
        {
            "id": "saudi_job_aramco_cloud",
            "company_name": "Aramco Digital",
            "company_description": "Aramco Digital develops cloud, data, and industrial software platforms for enterprise-scale operations.",
            "job_title": "Cloud Platform Engineer",
            "job_description": "Support cloud-native platform services, container workloads, and deployment automation for digital transformation initiatives.",
            "requirements": [
                "Hands-on cloud or infrastructure engineering experience",
                "Understanding of containers and deployment pipelines",
                "Ability to troubleshoot distributed systems issues",
            ],
            "category": "jobs",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Dhahran",
            "salary": "16000-22000 SAR/month",
            "required_skills": ["Docker", "Kubernetes", "Linux", "AWS", "CI/CD"],
            "application_email": "digitalcareers@aramco.com",
            "posted_days_ago": 9,
            "deadline_days_after_posted": 28,
        },
        {
            "id": "saudi_job_sabic_security",
            "company_name": "SABIC",
            "company_description": "SABIC operates large industrial and digital systems with strong security and reliability requirements.",
            "job_title": "Cybersecurity Analyst",
            "job_description": "Monitor security events, support incident response, and strengthen baseline security controls across enterprise applications.",
            "requirements": [
                "Understanding of common security monitoring workflows",
                "Ability to document incidents and remediation actions",
                "Knowledge of cloud and endpoint security concepts",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Jubail",
            "salary": "13000-17000 SAR/month",
            "required_skills": ["Cybersecurity", "Linux", "AWS", "Incident Response", "Git"],
            "application_email": "earlycareers@sabic.com",
            "posted_days_ago": 12,
            "deadline_days_after_posted": 26,
        },
        {
            "id": "saudi_job_neom_frontend",
            "company_name": "NEOM",
            "company_description": "NEOM builds digital-first experiences and services across smart city, mobility, and enterprise initiatives.",
            "job_title": "Frontend Engineer",
            "job_description": "Create web interfaces for citizen and enterprise products with a focus on accessibility, performance, and design quality.",
            "requirements": [
                "Experience building modern React interfaces",
                "Strong front-end fundamentals and component design",
                "Ability to work closely with designers and backend teams",
            ],
            "category": "jobs",
            "work_type": "remote",
            "employment_type": "full-time",
            "location": "Neom",
            "salary": "14500-18500 SAR/month",
            "required_skills": ["React", "TypeScript", "JavaScript", "CSS", "Git"],
            "application_email": "talent@neom.com",
            "posted_days_ago": 2,
            "deadline_days_after_posted": 20,
        },
        {
            "id": "saudi_job_tamara_backend",
            "company_name": "Tamara",
            "company_description": "Tamara is a Saudi fintech company building consumer payments and merchant platforms across the region.",
            "job_title": "Backend Software Engineer",
            "job_description": "Build payment platform services, merchant APIs, and operational tooling with strong reliability and observability standards.",
            "requirements": [
                "Strong backend engineering fundamentals",
                "Experience with APIs, databases, and service monitoring",
                "Ability to ship production code in a fast-paced environment",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "17000-23000 SAR/month",
            "required_skills": ["Python", "FastAPI", "PostgreSQL", "Docker", "Microservices"],
            "application_email": "careers@tamara.co",
            "posted_days_ago": 0,
            "deadline_days_after_posted": 16,
        },
        {
            "id": "saudi_job_jahez_data",
            "company_name": "Jahez",
            "company_description": "Jahez operates consumer logistics and e-commerce platforms serving large volumes of delivery and marketplace traffic.",
            "job_title": "Data Analyst",
            "job_description": "Work with product and operations teams to analyze business performance, delivery trends, and experimentation results.",
            "requirements": [
                "Strong SQL and spreadsheet/dashboarding ability",
                "Comfort communicating insights to non-technical teams",
                "Python experience is a plus for automation and analysis",
            ],
            "category": "jobs",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "10000-13500 SAR/month",
            "required_skills": ["SQL", "Data Analysis", "Python", "Pandas"],
            "application_email": "jobs@jahez.net",
            "posted_days_ago": 5,
            "deadline_days_after_posted": 17,
        },
        {
            "id": "saudi_job_foodics_fullstack",
            "company_name": "Foodics",
            "company_description": "Foodics develops restaurant-tech platforms, POS systems, and merchant products used across Saudi Arabia and MENA.",
            "job_title": "Full Stack Engineer",
            "job_description": "Build merchant-facing dashboards and APIs that support restaurant operations and analytics workflows.",
            "requirements": [
                "Experience across frontend and backend delivery",
                "Ability to work with modern TypeScript and API stacks",
                "Strong ownership and collaboration habits",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Jeddah",
            "salary": "13000-17500 SAR/month",
            "required_skills": ["React", "TypeScript", "Node.js", "SQL", "Docker"],
            "application_email": "careers@foodics.com",
            "posted_days_ago": 8,
            "deadline_days_after_posted": 25,
        },
        {
            "id": "saudi_job_alrajhi_cloud",
            "company_name": "Al Rajhi Bank",
            "company_description": "Al Rajhi Bank operates large-scale digital banking systems and customer channels across Saudi Arabia.",
            "job_title": "Cloud Operations Engineer",
            "job_description": "Support deployment pipelines, cloud services, and platform operations for digital banking workloads.",
            "requirements": [
                "Experience with cloud operations or DevOps practices",
                "Knowledge of incident handling and production support",
                "Comfort working with automation and deployment tooling",
            ],
            "category": "jobs",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "14000-19500 SAR/month",
            "required_skills": ["AWS", "Docker", "Linux", "CI/CD", "Terraform"],
            "application_email": "graduateprogram@alrajhibank.com.sa",
            "posted_days_ago": 11,
            "deadline_days_after_posted": 23,
        },
        {
            "id": "saudi_job_snb_security",
            "company_name": "SNB",
            "company_description": "SNB runs enterprise banking and digital channels that require strong governance, security, and resilience.",
            "job_title": "Application Security Engineer",
            "job_description": "Partner with engineering teams to improve secure delivery standards, review applications, and support remediation planning.",
            "requirements": [
                "Understanding of secure software development practices",
                "Ability to communicate findings and work with engineers",
                "Knowledge of authentication and web security concepts",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Jeddah",
            "salary": "15000-20000 SAR/month",
            "required_skills": ["Cybersecurity", "REST API", "Git", "Linux", "API Design"],
            "application_email": "careers@snb.com.sa",
            "posted_days_ago": 14,
            "deadline_days_after_posted": 14,
        },
        {
            "id": "saudi_job_riyadbank_product",
            "company_name": "Riyad Bank",
            "company_description": "Riyad Bank is expanding digital banking products and internal platforms for retail and enterprise banking.",
            "job_title": "Digital Product Coordinator",
            "job_description": "Coordinate product backlog updates, delivery tracking, and cross-functional communication for digital banking initiatives.",
            "requirements": [
                "Organized execution and product coordination ability",
                "Comfort documenting user stories and acceptance criteria",
                "Exposure to data-driven product decisions is valuable",
            ],
            "category": "jobs",
            "work_type": "hybrid",
            "employment_type": "part-time",
            "location": "Riyadh",
            "salary": "7000-9500 SAR/month",
            "required_skills": ["Product Management", "SQL", "Communication", "Data Analysis"],
            "application_email": "careers@riyadbank.com",
            "posted_days_ago": 4,
            "deadline_days_after_posted": 19,
        },
        {
            "id": "saudi_coop_stc_frontend",
            "company_name": "STC",
            "company_description": "STC offers student placements across digital product and engineering teams.",
            "job_title": "Frontend Coop Trainee",
            "job_description": "Support web UI feature delivery, testing, and component implementation in a product engineering squad.",
            "requirements": [
                "Current student in Computer Science, SWE, or related field",
                "Good foundation in JavaScript and frontend development",
                "Willingness to learn collaborative engineering workflows",
            ],
            "category": "coop",
            "work_type": "in-person",
            "employment_type": "part-time",
            "location": "Riyadh",
            "salary": "2500-3500 SAR/month",
            "required_skills": ["React", "JavaScript", "TypeScript", "CSS"],
            "application_email": "coop@stc.com.sa",
            "posted_days_ago": 2,
            "deadline_days_after_posted": 15,
        },
        {
            "id": "saudi_coop_elm_backend",
            "company_name": "Elm",
            "company_description": "Elm offers coop placements for students interested in government-tech and digital services.",
            "job_title": "Backend Coop Trainee",
            "job_description": "Assist backend teams with internal tooling, API integrations, and testing under mentor guidance.",
            "requirements": [
                "Strong learning mindset and basic backend programming skills",
                "Understanding of APIs and data persistence concepts",
                "Availability for a structured coop term",
            ],
            "category": "coop",
            "work_type": "hybrid",
            "employment_type": "part-time",
            "location": "Riyadh",
            "salary": "3000-4000 SAR/month",
            "required_skills": ["Python", "FastAPI", "SQL", "Git"],
            "application_email": "students@elm.sa",
            "posted_days_ago": 7,
            "deadline_days_after_posted": 18,
        },
        {
            "id": "saudi_coop_sdaia_data",
            "company_name": "SDAIA",
            "company_description": "SDAIA coop opportunities expose students to national-scale data and AI workstreams.",
            "job_title": "Data Science Coop Trainee",
            "job_description": "Support data prep, reporting, and experimentation tasks for analytics and AI initiatives.",
            "requirements": [
                "Current student in data, AI, or software-related major",
                "Basic Python and statistics foundation",
                "Ability to work with notebooks and datasets",
            ],
            "category": "coop",
            "work_type": "hybrid",
            "employment_type": "part-time",
            "location": "Riyadh",
            "salary": "3000-4200 SAR/month",
            "required_skills": ["Python", "Pandas", "Machine Learning", "SQL"],
            "application_email": "students@sdaia.gov.sa",
            "posted_days_ago": 10,
            "deadline_days_after_posted": 12,
        },
        {
            "id": "saudi_coop_foodics_product",
            "company_name": "Foodics",
            "company_description": "Foodics hosts coop students inside product and merchant experience teams.",
            "job_title": "Product Operations Coop",
            "job_description": "Help track product requests, support release prep, and document merchant-facing workflow improvements.",
            "requirements": [
                "Strong written communication and organization",
                "Interest in SaaS products and merchant tooling",
                "Comfort with spreadsheets or simple analytics tools",
            ],
            "category": "coop",
            "work_type": "remote",
            "employment_type": "part-time",
            "location": "Jeddah",
            "salary": "2500-3200 SAR/month",
            "required_skills": ["Product Management", "Data Analysis", "Communication"],
            "application_email": "students@foodics.com",
            "posted_days_ago": 1,
            "deadline_days_after_posted": 14,
        },
        {
            "id": "saudi_gdp_aramco_backend",
            "company_name": "Aramco Digital",
            "company_description": "Aramco Digital graduate programs prepare early-career engineers for enterprise platform and digital product work.",
            "job_title": "Graduate Development Program - Backend Track",
            "job_description": "A structured graduate program focused on backend engineering, cloud fundamentals, software quality, and cross-team delivery.",
            "requirements": [
                "Recent graduate in Computer Science, Software Engineering, or related discipline",
                "Strong programming fundamentals and growth mindset",
                "Ability to relocate or work on-site in the Eastern Province",
            ],
            "category": "gdp",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Dhahran",
            "salary": "9000-11500 SAR/month",
            "required_skills": ["Python", "FastAPI", "SQL", "Docker", "Git"],
            "application_email": "graduatecareers@aramco.com",
            "posted_days_ago": 13,
            "deadline_days_after_posted": 20,
        },
        {
            "id": "saudi_gdp_sabic_cloud",
            "company_name": "SABIC",
            "company_description": "SABIC's graduate tracks expose new hires to digital manufacturing, cloud services, and enterprise platform teams.",
            "job_title": "Graduate Program - Cloud & Infrastructure",
            "job_description": "Join a rotational graduate track covering cloud operations, automation, and platform engineering practices.",
            "requirements": [
                "Recent graduate in IT, software, or systems discipline",
                "Interest in cloud and infrastructure engineering",
                "Ability to learn in structured rotational environments",
            ],
            "category": "gdp",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Jubail",
            "salary": "8500-11000 SAR/month",
            "required_skills": ["AWS", "Docker", "Linux", "Terraform"],
            "application_email": "earlycareers@sabic.com",
            "posted_days_ago": 16,
            "deadline_days_after_posted": 18,
        },
        {
            "id": "saudi_gdp_neom_data",
            "company_name": "NEOM",
            "company_description": "NEOM graduate pathways include digital city data and analytics roles for high-growth early-career talent.",
            "job_title": "Graduate Program - Data & AI",
            "job_description": "Support data products, analytics workflows, and AI experimentation in a multidisciplinary graduate environment.",
            "requirements": [
                "Recent graduate with strong quantitative foundation",
                "Interest in data platforms, reporting, and AI workflows",
                "Ability to work with multidisciplinary product teams",
            ],
            "category": "gdp",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Neom",
            "salary": "9500-12500 SAR/month",
            "required_skills": ["Python", "SQL", "Machine Learning", "Pandas"],
            "application_email": "graduates@neom.com",
            "posted_days_ago": 5,
            "deadline_days_after_posted": 22,
        },
        {
            "id": "saudi_gdp_alrajhi_security",
            "company_name": "Al Rajhi Bank",
            "company_description": "Al Rajhi Bank runs graduate pathways for technology, operations, and risk with a strong digital banking focus.",
            "job_title": "Graduate Program - Cybersecurity",
            "job_description": "A structured graduate experience across security operations, application risk, and digital banking protection initiatives.",
            "requirements": [
                "Recent graduate in cybersecurity, IT, or software field",
                "Interest in secure systems and enterprise operations",
                "Good communication and documentation discipline",
            ],
            "category": "gdp",
            "work_type": "in-person",
            "employment_type": "full-time",
            "location": "Riyadh",
            "salary": "8500-10500 SAR/month",
            "required_skills": ["Cybersecurity", "Linux", "REST API", "Git"],
            "application_email": "graduateprogram@alrajhibank.com.sa",
            "posted_days_ago": 20,
            "deadline_days_after_posted": 10,
        },
        {
            "id": "saudi_gdp_snb_product",
            "company_name": "SNB",
            "company_description": "SNB's graduate intake includes digital product, data, and technology tracks supporting modern banking channels.",
            "job_title": "Graduate Program - Digital Product",
            "job_description": "Work with digital banking teams on product delivery, analytics, customer journeys, and cross-functional execution.",
            "requirements": [
                "Recent graduate interested in digital product and banking",
                "Comfort with structured analysis and stakeholder communication",
                "Strong curiosity about technology-enabled services",
            ],
            "category": "gdp",
            "work_type": "hybrid",
            "employment_type": "full-time",
            "location": "Jeddah",
            "salary": "8000-10000 SAR/month",
            "required_skills": ["Product Management", "SQL", "Data Analysis", "Communication"],
            "application_email": "graduates@snb.com.sa",
            "posted_days_ago": 18,
            "deadline_days_after_posted": 16,
        },
    ]

    @staticmethod
    def _build_runtime_dates(posted_days_ago: int, deadline_days_after_posted: int) -> dict[str, str | bool]:
        """Generate realistic runtime-relative posting and deadline fields."""
        now = datetime.now(timezone.utc)
        posted_at = now - timedelta(days=posted_days_ago)
        deadline = posted_at + timedelta(days=deadline_days_after_posted)
        is_open = deadline >= now
        return {
            "posted_at": posted_at.isoformat(),
            "application_deadline": deadline.isoformat(),
            "is_open": is_open,
        }

    @staticmethod
    def _build_opportunity(template: dict[str, Any]) -> dict[str, Any]:
        """Convert a template into the canonical opportunity schema."""
        dates = SaudiDemoOpportunitiesService._build_runtime_dates(
            template["posted_days_ago"],
            template["deadline_days_after_posted"],
        )
        application_email = template["application_email"]

        return {
            "id": template["id"],
            "company_name": template["company_name"],
            "company_description": template["company_description"],
            "job_title": template["job_title"],
            "job_description": template["job_description"],
            "requirements": template["requirements"],
            "category": template["category"],
            "work_type": template["work_type"],
            "employment_type": template["employment_type"],
            "working_time": "20 hours/week" if template["employment_type"] == "part-time" else "40 hours/week",
            "location": template["location"],
            "salary": template["salary"],
            "required_skills": template["required_skills"],
            "application_email": application_email,
            "apply_url": f"mailto:{application_email}",
            "posted_at": dates["posted_at"],
            "application_deadline": dates["application_deadline"],
            "is_open": dates["is_open"],
            "source": "saudi_demo",
        }

    @staticmethod
    def get_opportunities() -> list[dict[str, Any]]:
        """Return all generated Saudi demo opportunities."""
        return [SaudiDemoOpportunitiesService._build_opportunity(template) for template in SaudiDemoOpportunitiesService._TEMPLATES]

    @staticmethod
    def get_open_opportunities() -> list[dict[str, Any]]:
        """Return only currently open opportunities for the main feed."""
        return [opp for opp in SaudiDemoOpportunitiesService.get_opportunities() if opp.get("is_open")]
